// Imports the Ticket model so that this controller can create
// and receive Ticket objects.
using LU2TicketMvc.Models;

// Imports ASP.NET Core MVC classes such as Controller,
// IActionResult, HttpGet and HttpPost.
using Microsoft.AspNetCore.Mvc;

// Places this controller inside the Controllers namespace.
namespace LU2TicketMvc.Controllers;

// Declares the HomeController class.
// Every MVC controller must inherit from the Controller class.
public class HomeController : Controller
{
    // Stores the number that will be assigned to the next ticket.
    // The value is static so that it is shared by all requests
    // while the application is running.
    private static int nextTicketId = 1;

    // HTTP GET is used when the browser requests information
    // or asks the application to display a page.
    [HttpGet]

    // Declares the Index action method.
    // This action opens the ticket form.
    public IActionResult Index()
    {
        // Creates a new Ticket object.
        // The Status property receives "Open" from the default
        // value that was specified inside the Ticket model.
        Ticket ticket = new Ticket();

        // Sends the Ticket object to Views/Home/Index.cshtml.
        // The View will use this object to display the form fields.
        return View(ticket);
    }

    // HTTP POST is used when the browser sends information
    // to the application, such as information entered into a form.
    [HttpPost]

    // Protects the form against cross-site request forgery attacks.
    // The form generated by the MVC tag helper automatically
    // creates the required security token.
    [ValidateAntiForgeryToken]

    // Declares the action that receives the completed form.
    // ASP.NET Core Model Binding reads the submitted form fields
    // and places their values inside the Ticket object.
    public IActionResult SubmitTicket(Ticket ticket)
    {
        // Sets the ticket status on the server.
        // The application controls the status rather than trusting
        // a value that may have been changed in the browser.
        ticket.Status = "Open";

        // Checks whether the submitted data satisfies the
        // validation rules declared inside the Ticket model.
        if (!ModelState.IsValid)
        {
            // Returns the user to the Index View when the data
            // is invalid.
            // The submitted Ticket object is returned so that
            // the user does not lose the values they entered.
            return View("Index", ticket);
        }

        // Assigns the current temporary ticket number.
        ticket.Id = nextTicketId;

        // Increases the number so that the next ticket receives
        // a different ID.
        nextTicketId++;

        // Opens the TicketConfirmation View.
        // The completed Ticket object is sent to the View so that
        // its information can be displayed.
        return View("TicketConfirmation", ticket);
    }

    // HTTP GET is used because the Privacy action only displays
    // a page and does not submit or change information.
    [HttpGet]

    // Keeps the Privacy page from the original MVC template working.
    public IActionResult Privacy()
    {
        // Opens Views/Home/Privacy.cshtml.
        return View();
    }
}